name: Build and deploy ASP.Net Core app to Azure Web App - email-campaign-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_FOLDER: dotnet6-postgresql-crud-application
  PUBLISH_DIR: publish_output

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_FOLDER }}

      - name: Build the project
        run: dotnet build ${{ env.PROJECT_FOLDER }} --configuration Release --no-restore

      - name: Publish the project for Linux
        run: dotnet publish ${{ env.PROJECT_FOLDER }} -c Release -r linux-x64 --self-contained false -o ${{ env.PUBLISH_DIR }}

      - name: Upload published artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'email-campaign-backend'
          slot-name: 'Production'
          package: ${{ env.PUBLISH_DIR }}
